### ISSUE TITLE
On modules, add left click that brings up the new stock crew transfer window

### ISSUE THREAD

**Issue by jyanjyanjyan** [sumghai/FusTek_StationParts#43]
Brings up same or similar menu as when you left click a hatch on stock parts (EVA/Transfer).

Will potentially get rid of Ship Manifest dependency.

**Comment by sumghai** [comment]
This is pretty much up to SQUAD now, but I'll keep poking dev **Mu** with my suggestion.

**Comment by sumghai** [comment]
KSP 1.0.5 now provides the crew transfer menu via right-click as a stock game feature, so this is now fully resolved.
