### ISSUE TITLE
Lag when modules get in range

### ISSUE THREAD

**Issue by hipy** [sumghai/FusTek_StationParts#48]
Hi,

For some reason there is an insane amount of lag when 2 modules get in range. It's unplayable.
As soon as you dock(managed it once despite the lag) the lag is gone.

In the dev thread someone mentioned it was the docking ports. I tried with stock but still had the same problem sadly.

Tried to dock 2 of those:
![2015-03-05_00001](https://cloud.githubusercontent.com/assets/1358013/6506219/a3682a0e-c349-11e4-8c68-096ed986298b.jpg)

**Comment by sumghai** [comment]
If you had a stripped-down installation of KSP with only FusTek and its dependencies (no cloud packs or anything else), are you able to reproduce the issue?

Does pointing the camera away from Kerbin help?

**Comment by sumghai** [comment]
Issue closed because reporting user failed to follow recommended diagnosticc procedures in a timely manner.
