### ISSUE TITLE
Misaligned UV mapping on Warehouse/Payload Bay module_id_symbols

### ISSUE THREAD

**Issue by sumghai** [sumghai/FusTek_StationParts#50]
As reported by **@InsaneDruid** on the KSP forums:

> Sorry if it was asked before: could you PLEASE fix the UV-Mapping of both the warehouse and payload modules "module_id_symbol"?
While the other ones (hab/science etc) are mapped to a 256*256 part of the main texture (to avoid ugly seams) the ones of the warehouse and payload module are off, so that you need a 257*257 part of the main texture to have aligning texture parts on the main skin and the icon skin (and either shrinking it to 256*256 for power of two textures or leaving it as 257*257). This can be seen on the default and alt textures, as the bump map is off one pixel at most of the modules.
>
> While it can be worked around for the warehouse, especially the layout of the payload module is a skinners nightmare. PLEASE delete one side (or both, as they don't align with the other modules icons anyway) or make two separate uv maps for the left and right side. PLEASE!. You already needed to flip the text 90 degree to work around the mirroring, but you can't mirror normal maps (as the normals on eeither side NEED to be different). I am making a skin that uses high detailed normalmaps, and you cannot avoid the most ugly seams on one side of the payload module, as the normal map gets mirrored. The icing on the cake is that the uv layouts of both sides don't align, so one side is mirrored AND shifted by several pixels. Again: not aproblem for plain "one color" skins, but the worst nightmare for a detailled skin.
PLEASE!

**Comment by sumghai** [comment]
The Warehouse module's module_id_symbol was an easy fix - all I did was reposition a couple of UV vertices (c54a9c4).

I'll get to the Payload Bay module in a moment.

**Comment by sumghai** [comment]
Payload Bay module UV mapping has been fixed as well (e5772d9).

I created a second Payload Bay icon texture ( **fustek_station_icon_payload2_texture.png** ), while reusing the same normal map for both icons. I'll update the Payload Bay CFG files and the MM patches tomorrow morning to support these changes.

Note to self - the new extra mesh is called **module_id_symbol_2**.

**Comment by sumghai** [comment]
CFG files and MM patches updated with additional reference to the new second Payload Bay icon (61c86c1).

Over to you to final testing and approval, @InsaneDruid - I know you'll want to update some of your textures in light of my fixes.

**Comment by InsaneDruid** [comment]
Testing done, all parts are good now. MLi Textures updated. I'll close this issue.
