### ISSUE TITLE
Migration to DDS textures

### ISSUE THREAD

**Issue by sumghai** [sumghai/FusTek_StationParts#51]
The upcoming 1.0 version of KSP will natively support DirectDraw Surface (DDS) textures, which can be directly loaded from disk and pushed to graphic cards, resulting in significant load time savings (compared with MBMs, PNGs and TGAs, which need to be decompressed and then recompressed to the correct format).

As such, it would be wise to transition to this texture format in the next release of this parts pack.

**Notes**
 - It would be wise to wait for KSP 1.0 to actually be released, so that one could actually evaluate the new DDS format stock part textures, and determine how to best perform the conversion
 - According to KSP developer Mu:
    - RGB Diffuse textures need to be DXT1, RGBA Diffuse with Alpha textures need to be DXT5 and normal maps need to be DXTnm
    - When converting, the -flip command is required, as DDS uses a different coordinate system to PNG/TGA

**Comment by sumghai** [comment]
KSP 1.0 has been released, and all stock parts now officially use DDS textures.

Since I currently don't have access to a laptop capable of running the game, I'll need to get volunteers to test converted FusTek textures.

[KSP to DDS texture converter](http://forum.kerbalspaceprogram.com/threads/98672-WIN-KSP-to-DDS-texture-converter) looks like the tool for the job - it's an standalone tool, automatically handles PNGs and performs the correct format conversion / flipping.

**Comment by sumghai** [comment]
Interesting observation from forum user **blowfish**:

> DDSLoader previously required textures to be flipped. That may not be the case with the stock loader now (haven't checked). If dds4ksp is causing in-game flipped textures, toggle the flip textures settings in the conversion options before reconverting (it defaults to true).

**Comment by InsaneDruid** [comment]
I could do it, probably using kompressonator (from ati) as this produces very nice dds and has tons of options. I would test-convert the "stock" ones and if all goes well i'll update my textures, too

**Comment by sumghai** [comment]
Okay, just used Blender and @taniwha-qf's .mu importer/exporter script, and found out that DDS textures for KSP are in fact flipped vertically:

![ksp texture format comparison](https://cloud.githubusercontent.com/assets/4993380/7365222/60cd2dc0-ede2-11e4-8fce-2544504ca0ed.png)

I did a test run on one of the FusTek textures using KSP2DDS, and it was flipped correctly (according to thumbnail previews) - obviously someone will need to test them out properly in-game, but I think I'll be able to convert my own textures myself :)

**Comment by sumghai** [comment]
The default FusTek classic textures have been converted to DDS.

@InsaneDruid and all other alt texture pack authors - you can convert yours at your own discretion.
