### ISSUE TITLE
Transparent windows on modules are grey when viewed from IVA of another module

### ISSUE THREAD

**Issue by sumghai** [sumghai/FusTek_StationParts#55]
At present, when sitting in the IVA space of one transparent pod and viewing another transparent pod, the RasterPropMonitor plugin is forced to make the windows of the latter opaque (due to issues with stock IVA cameras and transforms).

The FusTek modules' transparent windows display a grey texture in the opaque state, which doesn't really look nice. It is desirable to replace the grey with the one of the old frosted blue window diffuse, while still retaining the transparent windows when JSITransparentPod is active.

**Comment by sumghai** [comment]
Apparently, this has [something to do with RGB and alpha channels] (http://forum.kerbalspaceprogram.com/threads/57603-0-25-RasterPropMonitor-putting-the-A-in-your-IVA-%28v0-18-3%29-8-Oct?p=1257171&viewfull=1#post1257171):

> **@sumghai:** 
> Incidentally, how did you apply the custom blue window texture to the non-current pod? 

> **@nli2work:**
> that's a switch in JSITransparentPod module. still uses same texture. While the module is applied, it swaps windows with transparent shader so IVA is visible from outside; when viewing another pod with the same module from IVA, it swaps the other pod's windows with opaque shader to prevent rendering artifacts. 

> **@sumghai:** 
> I'm aware of the **opaqueShaderName** parameter, as I tested a dev build before 0.17 was released. My query is that for my windows, I already implemented a nearly-transparent smoked glass texture via **KSP/Alpha/Translucent Specular**, and if I apply the opaque shader, I get a flat grey texture. 

> **@nli2work:**
> I used diffuse/specular as default shader for the pod windows, and let the module swap it to transparent/specular. The texture is [32bit targa] (http://i.imgur.com/OhQkcga.jpg). The view from IVA is what the pod would look like without RPM. If you mean you see flat grey in Unity, I'm not sure. I get display issues with KSP shaders in unity, but usually they look fine in KSP. I only supplied the window transform for the **transparentTransforms** parameter. That seemed the easiest way of setting it up based on how I understand the documentation. 

> **@sumghai:** 
> The grey in my windows are only seen in-game on non-current pods. If I understand correctly, the texture on the left is your diffuse, and the one on the right is your transparency map? 

> **@nli2work:**
> it's single 32bit tga. left are RGB channels; right is Alpha channel. when the texture is used by opaque shader, the alpha channel won't do anything. on a transparent shader, the alpha channel gets applied. Haven't tried PNGs or MBM. maybe that's the cause? 

> **@sumghai:** 
> I think I understand now! I've been using Fireworks CS6 to do all my textures, and while it does support a full range of transparency, I don't think it can do alpha channels the same way Photoshop does. I'll probably experiment with this in the future, thanks! 

Will need to investigate if Fireworks CS5 supports Alpha channels for PNG, since that's the main tool for making mixed (vector and bitmap) elements on the FusTek textures.

I might also need to ask @nli2work whether KSP PartTools's texture export feature affects the Alpha channels.

**Comment by InsaneDruid** [comment]
PNG does not support alpha channels. PNG has transparency, yes, but that is not implemented via a separate alpha channel. Use TGA (full 32bit with 24bit RGB and 8 bit alpha) or dxt5 dds.

**Comment by sumghai** [comment]
> **@InsaneDruid:**
> PNG does not support alpha channels. PNG has transparency, yes, but that is not implemented via a separate alpha channel. Use TGA (full 32bit with 24bit RGB and 8 bit alpha) or dxt5 dds.

I'm tempted to avoid TGAs due to their extremely large file sizes and my unfamiliarity with the format (although I'm not sure if DXT5 DDS will actually be even larger than TGAs, given that DDS is an uncompressed file format ready to be directly pushed to graphics cards.

Also, apparently, PNG does support alpha channel transparency, but Photoshop doesn't have native support, so a free open-source plugin called SuperPNG is needed:

http://forum.kerbalspaceprogram.com/threads/69137-How-to-correctly-edit-a-PNG-file-with-alpha-channel

http://www.fnordware.com/superpng/

Anyway, I think I'll wait until 1.0 drops and when I can actually buy a laptop capable of running KSP before investigating this further.

**Comment by InsaneDruid** [comment]
DDS is not per definition uncompressed. Actually the most sub-formats are highly, even lossy compressed using s3 texture compression, achiving between 4:1 and 6:1 compression ratio. And, dds not only saves space on a harddisk, but needs the same amout of ram as an uncompressed file when opened, but stays compressed in vram. The latter one is the most important factor. While PNG can shrink the main mli texture from around 64MB (uncompressed TGA) to under 4MB, it will use 64MB Vram once its loaded. With DDS, it stays at 16MB (using dxt5/3dc to use the alpha channel for transparency on some parts and as a specular map for the other parts to control the specularity).

**Comment by sumghai** [comment]
I see - thanks for the comprehensive explanation.

So by the looks of things
 - The final format of the textures distributed in the download will be in DDS.
 - For ease of development, my source files will probably still be PNG (using Photoshop CS6 + SuperPNG plugin)

What do you reckon?

**Comment by InsaneDruid** [comment]
Yes, dds-export should be the last think before release, while keeping original sources.

**Comment by sumghai** [comment]
Given 5f0ff19 and #69, a fix for this isn't really needed anymore.

(I know that the Kupola viewports will end up remaining grey when viewed from another IVA, since it still uses JSITransparentPod, but Kupolas aren't used as often as Karmony crew modules, so this can be sidelined at the very least)
