### ISSUE TITLE
some textures problems

### ISSUE THREAD

**Issue by ricardo-zzz** [sumghai/FusTek_StationParts#65]
Hi, sumghai

there are a few texture issues I want to report (I don't know if you already has a new laptop to figure out by yourself).
the problems are:
-cant change texture (the feature was removed?)
-windows are transparent both in VAB and flying
-there is a strange cube inside doors on IVA

http://imgur.com/a/cPcwg

thanks for keeping this mod

**Comment by sumghai** [comment]
**Texture Switching**

Do you have the latest version of Firespitter installed?

**Windows are transparent both in VAB and flying**

Do you have JSI RasterPropMonitor installed?

**Strange cuboid near hatch**

That's just a button prop I made for testing purposes. Nothing to worry about.

**Comment by ricardo-zzz** [comment]
Wow, I forgot the dependencies, as I picked a fresh install to test mods before move into 1.0.x.

I'm very into your repo, and following uptades faithfully 

Anyway, Thanks for remembering.

**Comment by sumghai** [comment]
So just to confirm, once you've installed both dependencies, the problems have been resolved?

**Comment by sumghai** [comment]
Sounds like this is the case.

**Comment by ricardo-zzz** [comment]
sorry for delay, busy day here

yes, it is working, very nice to look inside modules, by the way
