### ISSUE TITLE
IACBM 2.5m clipps in passive mode

### ISSUE THREAD

**Issue by hraban35** [sumghai/FusTek_StationParts#67]
The inner tube of the IACBM 2.5m clips when passive mode is set. 
This clipping is a FPS killer. In my case the Framerate goes form 60 FPS to 20 FPS when one of the IACBM 2.5m change to passive mode.

Idea: reduce the diameter of the inner tube a bit.

**Comment by sumghai** [comment]
What do you mean by "clip" and "inner tube"? Could you please provide an (annotated) screenshot?

Additional questions:
 - Does the FPS reduction occur at the exact instant the 2.5m IACBM is switched to passive?
 - Does the FPS reduction remain after the 2.5m IACBM is switched to passive?
 - Does the FPS reduction remain after switching between vessels?
 - Does the FPS reduction remain after reloading the savegame / restarting the game?
 - Is this issue also present in the 1.25m IACBM?

**Comment by hraban35** [comment]
Unfortunately, my English is not so good, therefore it could be a little 
difficult.

The FPS-burglary I have been able to observe only with the IACBM 1.25m.
I'll test it at the other also.

The object flicker (clipping) can not hold in a screenshot.
Obviously, the cylinder of the active / passive ring overlap with the 
outer housing of the couplerduring switching.
The FPS-burglary takes about 60 seconds, after which it stabilizes again.
Ever, IACBM are FPS killer.
With more than 16 couplers my game goes on crutches.
Why so many coupler? Because I compose the station, module by module in 
orbit.

Best Regards

Ralf alias hraban

Am 04.07.2015 um 23:45 schrieb Robin Chang:

**Comment by sumghai** [comment]
Given that this predates the other issue you reported (#68), and that was solved by updating to the latest dev build on GitHub, please check the docking ports again, as the docking ports models would have already been optimized since then.

**Comment by sumghai** [comment]
Closed #67 due to lack of response.
