### ISSUE TITLE
Karmony Science Module Adapter miss Storage for Science

### ISSUE THREAD

**Issue by hraban35** [sumghai/FusTek_StationParts#68]
The Science Module cant store any researches.

**Comment by sumghai** [comment]
That doesn't sound right, since the latest version on GitHub **does** have the following PartModules like in the stock science lab:

 - ModuleScienceContainer
 - ModuleScienceLab
 - ModuleScienceConverter

What version of the parts pack do you have installed? Where did you download it from?

**Comment by hraban35** [comment]
Last Version does right. Close this Issue please.

**Comment by sumghai** [comment]
Closed #68.
