### ISSUE TITLE
Use gendered docking port options to mate only active + passive mode IACBMs

### ISSUE THREAD

**Issue by Bezzier** [sumghai/FusTek_StationParts#73]
KSP 1.0.5 supports gendered docking ports.  If possible to toggle docking port gender when switching modes, it might be a good idea to enforce gendered docking to only allow active + passive docking, and disable switching IACBM gender while docked.

**Comment by sumghai** [comment]
As the one who initially requested the gendered docking port feature on the KSP bugtracker, I know that the gender cannot be switched in-flight, so this feature isn't possible.
